name: coffee_shop
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter: 
    sdk: flutter

 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/bg.jpg
    - assets/logo.jpg
    - assets/profil.jpg
    - assets/biji.jpg
    - assets/ice.jpg
    - assets/kopi.jpg
    - assets/mesin.jpg
    - assets/latte.jpg
    - assets/coffee.jpg
    - assets/cup.jpg



